language: go
go: "1.14"
go_import_path: github.com/GoogleCloudPlatform/gcp-service-broker

install: true

services:
  - docker

jobs:
  include:
    - stage: test
      name: unit tests
      script: ./hack/test.sh
    - stage: test
      name: verify generated sources
      script: ./hack/verify-generated.sh
    - stage: build
      name: build docker image
      script: docker build -t gcp-service-broker .
