language: go
go: "1.14"
go_import_path: github.com/GoogleCloudPlatform/gcp-service-broker

# Skip the install step. Don't `go get` dependencies. Only build with the code in vendor/
install: skip

services:
  - docker

jobs:
  include:
    - stage: test
      name: unit tests
      script: ./hack/test.sh
    - stage: test
      name: verify generated sources
      script: ./hack/verify-generated.sh
    - stage: build
      name: build docker image
      script: docker build -t gcp-service-broker .
