language: go
go: "1.12"
go_import_path: github.com/GoogleCloudPlatform/gcp-service-broker

# Skip the install step. Don't `go get` dependencies. Only build with the code in vendor/
install: skip

services:
  - docker

script:
  - go test -v ./... -tags=service_broker
  - docker build -t gcp-service-broker .
