db:
  host: localhost
  name: servicebroker
  password: password
  port: "3306"
  user: root
  type: sqlite3
  path: test.sqlite3
api:
  user: user
  password: pass
  port: 8000

google.account: |-
  {
    "type": "service_account",
  }
