# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

ignored = ["github.com/GoogleCloudPlatform/gcp-service-broker/tools/osdfgen*"]

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/lager"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.0"

[[constraint]]
  name = "github.com/pivotal-cf/brokerapi"
  version = "4.2.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/hil"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"
  version = "v1.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.22.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-getter"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"

[[constraint]]
  branch = "master"
  name = "github.com/robertkrimen/otto"
