---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cloud-builders/go
inputs:
- name: gcp-service-broker
  path: broker-source
outputs:
- name: compiled-broker
  path: gsb-bin
run:
  dir: broker-source
  path: go.ash
  args: ['build', '-o', '../gsb-bin/gcp-service-broker']
params:
  PROJECT_ROOT: github.com/GoogleCloudPlatform/gcp-service-broker
