---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
inputs:
- name: gcp-service-broker-ci
- name: compiled-broker
run:
  path: gcp-service-broker-ci/ci/tasks/metadata.sh
