---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
- name: compiled-broker
- name: gcp-service-broker-ci

params:
  ROOT_SERVICE_ACCOUNT_JSON:
  DB_USERNAME:
  DB_PASSWORD:
  DB_HOST:

run:
  path: gcp-service-broker-ci/ci/tasks/osb-integration-tests.sh
