---
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: gcp-service-broker
    type: git
    source:
      uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
      branch: {{code_branch}}
      ignore_paths:
        - ci/*

  - name: gcp-service-broker-ci
    type: git
    source:
      uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
      branch: {{ci_branch}}
      paths:
        - ci/*

  - name: release
    type: gcs-resource
    source:
      bucket: {{artifacts_bucket_name}}
      json_key: {{artifacts_json_key}}
      regexp: gcp-service-broker-(.*).pivotal

jobs:
  - name: unit-test
    plan:
      - aggregate:
        - get: gcp-service-broker
          trigger: true
          params: {depth: 1}
        - get: gcp-service-broker-ci
          params: {depth: 1}
      - task: test
        file: gcp-service-broker-ci/ci/tasks/go-test.yml
      - task: build
        file: gcp-service-broker-ci/ci/tasks/go-build.yml

  - name: integration
    serial: true
    plan:
      - aggregate:
        - get: gcp-service-broker
          trigger: true
          passed: [unit-test]
          params: {depth: 1}
        - get: gcp-service-broker-ci
          params: {depth: 1}
      - task: build
        file: gcp-service-broker-ci/ci/tasks/go-build.yml
      - task: osb-integration-tests
        file: gcp-service-broker-ci/ci/tasks/osb-integration-tests.yml
        params:
          ROOT_SERVICE_ACCOUNT_JSON: {{integration_test_service_account_json}}
          DB_USERNAME: {{integration_test_db_username}}
          DB_PASSWORD: {{integration_test_db_password}}
          DB_HOST: {{integration_test_db_host}}

  - name: release
    plan:
      - aggregate:
        - get: gcp-service-broker
          trigger: true
          passed: [integration]
          params: {depth: 1}
        - get: gcp-service-broker-ci
          params: {depth: 1}
      - task: build
        file: gcp-service-broker-ci/ci/tasks/go-build.yml
      - task: metadata
        file: gcp-service-broker-ci/ci/tasks/metadata.yml
      - task: build-tile
        file: gcp-service-broker-ci/ci/tasks/build-tile.yml
      - task: bundle
        file: gcp-service-broker-ci/ci/tasks/bundle.yml
      - put: release
        params:
          file: bundle/*.zip
